include:
  - project: graphaware/devops/gitlab-ci-templates
    file: gitlab-ci-templates.yml

stages:
  - deploy
  - postDeploy


bumpVersion:
  extends: .frameworkVersionBump
  stage: deploy

uploadArtifact:
  extends: .uploadToS3
  stage: postDeploy
  dependencies:
    - bumpVersion
  variables:
    FROM: target/checkout/target/resttest-$VERSION.jar
    TO: $AWS_PATH/resttest-$VERSION.jar
  only:
    refs:
      - master
    variables:
      - $VERSION